#!/usr/bin/env python3
"""Generate tenants/workloads.yaml: one avalanche Deployment per (tenant, team).

The sizing table below is the single source of truth for how big each
simulated tenant is. Scenarios scale these deployments at runtime
(`make scale`), so this is the *baseline*, not a fixed state.

Run from dev/mimir-k8s:  ./scripts/gen-tenants.py
"""

WORKLOADS = [
    # tenant,     team,       gauge metrics, series per metric
    ("analytics", "bi",       20, 400),   # 8,000 series
    ("analytics", "ml",       10, 500),   # 5,000
    ("infra",     "sre",      20, 350),   # 7,000
    ("payments",  "payments", 10, 120),   # 1,200
    ("platform",  "platform",  2,  50),   #   100
]

NAMESPACE = """apiVersion: v1
kind: Namespace
metadata:
  name: tenants"""

DEPLOYMENT = """apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  namespace: tenants
  labels: {{app: avalanche, tenant: {tenant}, team: {team}}}
spec:
  replicas: 1
  selector:
    matchLabels: {{app: avalanche, tenant: {tenant}, team: {team}}}
  template:
    metadata:
      labels: {{app: avalanche, tenant: {tenant}, team: {team}}}
    spec:
      containers:
        - name: avalanche
          image: quay.io/prometheuscommunity/avalanche:v0.7.0
          args:
            # {metrics} x {series} = {total} active series per replica
            - --gauge-metric-count={metrics}
            - --series-count={series}
            - --label-count=5
            - --value-interval=15
            # Effectively no series churn. avalanche replaces every
            # series_id each --series-interval, and Mimir keeps the old
            # ones active for 20m — an hourly setting doubled every
            # tenant for 20m of each hour and wrecked the first scenario
            # run. Churn belongs in a scenario, not the baseline.
            - --series-interval=315360000
            - --metric-interval=0
            - --port=9001
          ports:
            - {{name: metrics, containerPort: 9001}}
          resources:
            requests: {{cpu: 10m, memory: 32Mi}}"""


def main() -> None:
    docs = [NAMESPACE]
    for tenant, team, metrics, series in WORKLOADS:
        name = f"avalanche-{tenant}" if tenant == team else f"avalanche-{tenant}-{team}"
        docs.append(DEPLOYMENT.format(
            name=name, tenant=tenant, team=team,
            metrics=metrics, series=series, total=metrics * series,
        ))
    with open("tenants/workloads.yaml", "w") as f:
        f.write("# Generated by scripts/gen-tenants.py — edit the table there, not this file.\n")
        f.write("\n---\n".join(docs) + "\n")


if __name__ == "__main__":
    main()
