#!/usr/bin/env python3
"""Generate grafana/obscost-dashboard.yaml: one dashboard showing each of
ADR 0003's per-tenant cost drivers side by side with what the Mimir
components actually consume, so a scenario's effect is visible in both.

Run from dev/mimir-k8s:  ./scripts/gen-dashboard.py
"""
import json

DS = {"type": "prometheus", "uid": "mimir-monitoring"}

# Real (deduplicated) active series per tenant, whichever write path the
# cluster runs: the classic branch divides by the replication factor, the
# ingest-storage branch collapses zone replicas of a partition. The same
# two forms promcost's pool-1 query uses (internal/cost/mimirdrivers).
ACTIVE_SERIES = (
    "(sum by (user) (cortex_ingester_active_series unless on (cluster, namespace, job) cortex_partition_ring_partitions)"
    " / on () group_left max(cortex_distributor_replication_factor))"
    " or sum by (user) (max by (ingester_id, user) (label_replace("
    "cortex_ingester_active_series and on (cluster, namespace, job) cortex_partition_ring_partitions,"
    ' "ingester_id", "$1", "pod", ".*?-(rc-[0-9]+-[0-9]+|[0-9]+)$")))'
)

ROWS = [
    ("Pool 1 — ingester memory", [
        ("Active series per tenant (real, deduplicated)", "timeseries", ACTIVE_SERIES, "{{user}}", "short", True),
        ("Share of ingester memory", "piechart", ACTIVE_SERIES, "{{user}}", "short", False),
        ("Active series by team (cost-attribution tracker, raw across ingesters)", "timeseries",
         "sum by (tenant, team) (cortex_ingester_attributed_active_series)", "{{tenant}}/{{team}}", "short", True),
    ]),
    ("Pool 2 — write path", [
        ("Samples received per tenant", "timeseries",
         "sum by (user) (rate(cortex_distributor_received_samples_total[1m]))", "{{user}}", "short", True),
    ]),
    ("Pools 6–7 — ruler and query path", [
        ("Rule evaluation time per tenant (s/s)", "timeseries",
         "sum by (user) (rate(cortex_prometheus_rule_evaluation_duration_seconds_sum[1m]))", "{{user}}", "s", True),
        ("Query time per tenant (s/s)", "timeseries",
         "sum by (user) (rate(cortex_query_seconds_total[1m]))", "{{user}}", "s", True),
    ]),
    ("What the components actually use (cAdvisor)", [
        ("Memory working set per component", "timeseries",
         'sum by (container) (container_memory_working_set_bytes{namespace="mimir"})', "{{container}}", "bytes", True),
        ("CPU per component", "timeseries",
         'sum by (container) (rate(container_cpu_usage_seconds_total{namespace="mimir"}[1m]))', "{{container}}", "cores", True),
        ("Ingester memory per active series (raw, incl. replicas)", "timeseries",
         'sum(container_memory_working_set_bytes{namespace="mimir", container="ingester"}) / sum(cortex_ingester_memory_series)',
         "bytes per series", "bytes", False),
    ]),
]


def panel(pid, title, kind, expr, legend, unit, stacked, x, y, w):
    p = {
        "id": pid, "title": title, "type": kind, "datasource": DS,
        "gridPos": {"x": x, "y": y, "w": w, "h": 8},
        "targets": [{"refId": "A", "datasource": DS, "expr": expr, "legendFormat": legend}],
        "fieldConfig": {"defaults": {"unit": unit}, "overrides": []},
        "options": {"legend": {"displayMode": "table", "placement": "right", "calcs": ["lastNotNull"]}},
    }
    if kind == "timeseries":
        p["fieldConfig"]["defaults"]["custom"] = {
            "stacking": {"mode": "normal" if stacked else "none"}, "fillOpacity": 20 if stacked else 0}
    if kind == "piechart":
        p["targets"][0]["instant"] = True
        p["options"].update({"reduceOptions": {"calcs": ["lastNotNull"]}, "pieType": "donut",
                             "displayLabels": ["name", "percent"]})
    return p


def main():
    panels, pid, y = [], 1, 0
    for row_title, row_panels in ROWS:
        panels.append({"id": pid, "type": "row", "title": row_title, "collapsed": False,
                       "gridPos": {"x": 0, "y": y, "w": 24, "h": 1}, "panels": []})
        pid, y = pid + 1, y + 1
        w = 24 // len(row_panels) if len(row_panels) < 3 else 8
        for i, (title, kind, expr, legend, unit, stacked) in enumerate(row_panels):
            panels.append(panel(pid, title, kind, expr, legend, unit, stacked, (i * w) % 24, y, w))
            pid += 1
        y += 8
    dash = {
        "uid": "obscost-tenant-cost", "title": "obscost — tenant cost drivers",
        "schemaVersion": 39, "time": {"from": "now-1h", "to": "now"}, "refresh": "30s",
        "tags": ["obscost"], "panels": panels,
    }
    body = json.dumps(dash, indent=2)
    with open("grafana/obscost-dashboard.yaml", "w") as f:
        f.write("# Generated by scripts/gen-dashboard.py — edit the panel table there.\n")
        f.write("apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: obscost-dashboard\n  namespace: mimir\n")
        f.write("  labels: {grafana_dashboard: \"1\"}\n")
        f.write("  annotations: {k8s-sidecar-target-directory: /tmp/dashboards/obscost}\n")
        f.write("data:\n  obscost-tenant-cost.json: |-\n")
        f.write("\n".join("    " + line for line in body.splitlines()) + "\n")


if __name__ == "__main__":
    main()
